#MAC ID configuration, For Test purpose only
MDIOBUSID1: 1: MAC_ID1: EC:21:E5:00:4F:EA
MDIOBUSID2: 2: MAC_ID2: EC:21:E5:01:4F:EA
MDIOBUSID3: 3: MAC_ID3: EC:21:E5:02:4F:EA
MDIOBUSID4: 4: MAC_ID4: EC:21:E5:03:4F:EA
MDIOBUSID5: 5: MAC_ID5: EC:21:E5:04:4F:EA
MDIOBUSID6: 6: MAC_ID6: EC:21:E5:05:4F:EA
MDIOBUSID7: 7: MAC_ID7: EC:21:E5:06:4F:EA
MDIOBUSID8: 8: MAC_ID8: EC:21:E5:07:4F:EA
#End of file (New line)
