obj-$(CONFIG_TOSHIBA_PCIE_EMAC) += DWC_ETH_QOS.o
DWC_ETH_QOS-y := DWC_ETH_QOS_dev.o \
			DWC_ETH_QOS_drv.o \
			DWC_ETH_QOS_desc.o \
			DWC_ETH_QOS_ethtool.o \
			DWC_ETH_QOS_pci.o \
			DWC_ETH_QOS_mdio.o \
			DWC_ETH_QOS_eee.o \
			DWC_ETH_QOS_sysfs_registers.o

DWC_ETH_QOS-$(CONFIG_TOSHIBA_PCIE_EMAC_PTPSUPPORT) += DWC_ETH_QOS_ptp.o
